version: "3.8"

services:
  web:
    image: alpermuhacir/magic5-website:latest
    container_name: magic5-website
    restart: unless-stopped
    ports:
      - "8080:80"
    labels:
      - "com.casaos.appid=magic5-website"
      - "com.casaos.appname=Magic5 website"
      - "com.casaos.appurl=http://localhost:8080"
      - "com.casaos.category=media"
      - "com.casaos.description=Localized Magic5 Website (TR/EN)"
